"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = [('', ['config.py', 'requirements.txt'])]
OPTIONS = {
    'argv_emulation': False,
    'packages': ['tkinter', 'tkcalendar'],
    'includes': ['matplotlib', 'numpy', 'pandas'],
    'excludes': ['tkinter.test'],
    'plist': {
        'CFBundleName': 'MyWeightTracker',
        'CFBundleDisplayName': 'MyWeightTracker',
        'CFBundleIdentifier': 'com.myweighttracker',
        'CFBundleVersion': '1.0.0',
        'CFBundleShortVersionString': '1.0.0'
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
) 